version: '2.1'
services:
  api:
    container_name: ${APP}
    build:
      context: .
      args:
        proxy: ${http_proxy}
        app_name: ${APP}
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app/tmp:/app/app/tmp
    mem_limit: 500000000
    memswap_limit: 6000000000
networks:
  default:
    external:
      name: ${APP}
